spring:
  jpa:
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
